{% set name = "coverage" %}
{% set version = "7.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coverage-{{ version }}.tar.gz
  sha256: 36dd42da34fe94ed98c39887b86db9d06777b1c8f860520e21126a75507024f2

build:
  number: 0
  skip: True  # [py<37]
  entry_points:
    - coverage = coverage.cmdline:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    # extra dependency to enable pyproject.toml support
    - tomli  # [py<311]

test:
  imports:
    - coverage
  requires:
    - pip
  commands:
    - pip check
    - coverage --help

about:
  home: https://coverage.readthedocs.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Code coverage measurement for Python
  description: |
    Coverage.py is a tool for measuring code coverage of Python programs. It
    monitors your program, noting which parts of the code have been executed,
    then analyzes the source to identify code that could have been executed
    but was not. Coverage measurement is typically used to gauge the
    effectiveness of tests. It can show which parts of your code are being
    exercised by tests, and which are not.
  doc_url: https://coverage.readthedocs.io/
  dev_url: https://github.com/nedbat/coveragepy

extra:
  recipe-maintainers:
    - ericmjl
    - jakirkham
    - ocefpaf
