{% set version = "6.0" %}

package:
  name: coverage
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/coverage/coverage-{{ version }}.tar.gz
  sha256: 17983f6ccc47f4864fd16d20ff677782b23d1207bf222d10e4d676e4636b0872

build:
  number: 2
  entry_points:
    - coverage = coverage.cmdline:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - coverage

  commands:
    - coverage --help

about:
  home: https://coverage.readthedocs.io
  license: Apache 2.0
  license_file: LICENSE.txt
  summary: Code coverage measurement for Python
  description: |
    Coverage.py is a tool for measuring code coverage of Python programs. It
    monitors your program, noting which parts of the code have been executed,
    then analyzes the source to identify code that could have been executed
    but was not. Coverage measurement is typically used to gauge the
    effectiveness of tests. It can show which parts of your code are being
    exercised by tests, and which are not.
  doc_url: http://coverage.readthedocs.org
  dev_url: https://bitbucket.org/ned/coveragepy
  doc_source_url: https://bitbucket.org/ned/coveragepy/src/default/doc/?at=default

extra:
  recipe-maintainers:
    - ericmjl
    - jakirkham
    - ocefpaf
