{% set version = "5.0.2" %}

package:
  name: coverage
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/coverage/coverage-{{ version }}.tar.gz
  sha256: b251c7092cbb6d789d62dc9c9e7c4fb448c9138b51285c36aeb72462cad3600e

build:
  number: 0
  entry_points:
    - coverage = coverage.cmdline:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - coverage

  commands:
    - coverage --help

about:
  home: https://coverage.readthedocs.io
  license: Apache 2.0
  license_file: LICENSE.txt
  summary: 'Code coverage measurement for Python'

extra:
  recipe-maintainers:
    - ericmjl
    - jakirkham
    - ocefpaf
