{% set version = "6.2" %}

package:
  name: coverage
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/coverage/coverage-{{ version }}.tar.gz
  sha256: e2cad8093172b7d1595b4ad66f24270808658e11acf43a8f95b41276162eb5b8

build:
  number: 0
  entry_points:
    - coverage = coverage.cmdline:main
   skip: True  # [py<36]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - coverage
  requires:
    - pip
  commands:
    - coverage --help
    - pip check

about:
  home: https://coverage.readthedocs.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Code coverage measurement for Python
  description: |
    Coverage.py is a tool for measuring code coverage of Python programs. It
    monitors your program, noting which parts of the code have been executed,
    then analyzes the source to identify code that could have been executed
    but was not. Coverage measurement is typically used to gauge the
    effectiveness of tests. It can show which parts of your code are being
    exercised by tests, and which are not.
  doc_url: https://coverage.readthedocs.org
  dev_url: https://github.com/nedbat/coveragepy
  doc_source_url: https://github.com/nedbat/coveragepy/blob/master/doc/index.rst

extra:
  recipe-maintainers:
    - ericmjl
    - jakirkham
    - ocefpaf
