{% set name = "coverage" %}
{% set version = "7.13.4" %}
{% set deselect_tests = " --deselect=tests/test_regions.py::test_real_code_regions" %}
{% set deselect_tests = 'deselect_tests + " --deselect=tests/test_testing.py::test_all_our_source_files"' %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e5c8f6ed1e61a8b2dcdf31eb0b9bbf0130750ca79c1c49eb898e2ad86f5ccc91
  patches:
    - 0001-force-extension-module-creation.patch

build:
  number: 0
  skip: true  # [py<310]
  entry_points:
    - coverage = coverage.cmdline:main

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    # extra dependency to enable pyproject.toml support
    - tomli  # [py<311]

# E   where is_dir = (PosixPath('$SRC_DIR') / 'ci').is_dir
# ./ci/coverage/lab/tests is not in the pypi release tarball
test:
  source_files:
    - tests
  imports:
    - coverage
    - coverage.annotate
    - coverage.bytecode
    - coverage.cmdline
    - coverage.collector
    - coverage.config
    - coverage.context
    - coverage.control
    - coverage.core
    - coverage.data
    - coverage.debug
    - coverage.disposition
    - coverage.env
    - coverage.exceptions
    - coverage.execfile
    - coverage.files
    - coverage.html
    - coverage.inorout
    - coverage.jsonreport
    - coverage.lcovreport
    - coverage.misc
    - coverage.multiproc
    - coverage.numbits
    - coverage.parser
    - coverage.patch
    - coverage.phystokens
    - coverage.plugin
    - coverage.plugin_support
    - coverage.python
    - coverage.pytracer
    - coverage.regions
    - coverage.report
    - coverage.report_core
    - coverage.results
    - coverage.sqldata
    - coverage.sqlitedb
    - coverage.sysmon
    - coverage.templite
    - coverage.tomlconfig
    - coverage.tracer
    - coverage.types
    - coverage.version
    - coverage.xmlreport
  commands:
    - pip check
    - coverage --help
    - pytest -v tests {{ deselect_tests }}
  requires:
    - pip
    - pytest
    - hypothesis

about:
  home: https://coverage.readthedocs.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Code coverage measurement for Python
  description: |
    Coverage.py is a tool for measuring code coverage of Python programs. It
    monitors your program, noting which parts of the code have been executed,
    then analyzes the source to identify code that could have been executed
    but was not. Coverage measurement is typically used to gauge the
    effectiveness of tests. It can show which parts of your code are being
    exercised by tests, and which are not.
  doc_url: https://coverage.readthedocs.io
  dev_url: https://github.com/nedbat/coveragepy

extra:
  recipe-maintainers:
    - ericmjl
    - jakirkham
    - ocefpaf
