{% set name = "coverage" %}
{% set version = "6.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coverage-{{ version }}.tar.gz
  sha256: 03e2a7826086b91ef345ff18742ee9fc47a6839ccd517061ef8fa1976e652ce9

build:
  number: 0
  # trigger 1
  skip: True  # [py<37]
  entry_points:
    - coverage = coverage.cmdline:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  imports:
    - coverage
  requires:
    - pip
  commands:
    - pip check
    - coverage --help

about:
  home: https://coverage.readthedocs.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Code coverage measurement for Python
  description: |
    Coverage.py is a tool for measuring code coverage of Python programs. It
    monitors your program, noting which parts of the code have been executed,
    then analyzes the source to identify code that could have been executed
    but was not. Coverage measurement is typically used to gauge the
    effectiveness of tests. It can show which parts of your code are being
    exercised by tests, and which are not.
  doc_url: https://coverage.readthedocs.org
  dev_url: https://github.com/nedbat/coveragepy
  doc_source_url: https://github.com/nedbat/coveragepy/tree/6.2/doc

extra:
  recipe-maintainers:
    - ericmjl
    - jakirkham
    - ocefpaf
