{% set name = "coverage" %}
{% set version = "6.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/coverage-{{ version }}.tar.gz
  sha256: 6c3f6158b02ac403868eea390930ae64e9a9a2a5bbfafefbb920d29258d9f2f8

build:
  number: 0
  skip: True  # [py<37]
  entry_points:
    - coverage = coverage.cmdline:main

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    # Optional dependency: enable pyproject.toml support
    - tomli

test:
  imports:
    - coverage
  requires:
    - pip
  commands:
    - pip check
    - coverage --help

about:
  home: https://coverage.readthedocs.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: Code coverage measurement for Python
  description: |
    Coverage.py is a tool for measuring code coverage of Python programs. It
    monitors your program, noting which parts of the code have been executed,
    then analyzes the source to identify code that could have been executed
    but was not. Coverage measurement is typically used to gauge the
    effectiveness of tests. It can show which parts of your code are being
    exercised by tests, and which are not.
  doc_url: https://coverage.readthedocs.org
  dev_url: https://github.com/nedbat/coveragepy
  doc_source_url: https://github.com/nedbat/coveragepy/tree/6.2/doc

extra:
  recipe-maintainers:
    - ericmjl
    - jakirkham
    - ocefpaf
