{% set version = "4.3.1" %}
{% set hash = "fcc5838147c7b98871f32404ea9d60efc686ccca9adad3024291cb08c0b433cf" %}
{% set pkgname = "coverage" %}

package:
  name: {{ pkgname }}
  version: {{ version }}

source:
  fn: {{ pkgname }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ pkgname[0] }}/{{ pkgname }}/{{ pkgname }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  number: 0
  entry_points:
    - coverage = coverage.cmdline:main

requirements:
  build:
    - toolchain
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - coverage

  commands:
    - coverage --help

about:
  home: https://coverage.readthedocs.io
  license: Apache 2.0
  summary: 'Code coverage measurement for Python'

extra:
  recipe-maintainers:
    - ericmjl
    - jakirkham
    - ocefpaf
